### ISSUE TITLE
Inproper way of logging in the bot.

### ISSUE THREAD

**Issue by NorteX-dev** [realCartar/BeginnerBot#1]
Hi.
Just was browsing the repo, and found that the `bot.login("token");` function is at the top of the file. While this does not change anything functionality-wise, it's common practice to put the `bot.login()` method after all the events. If you want to give this repo as a foundation to new discord bot developers, it would be best if it was moved down. I know that probably nobody cares about this repo, but still.
Edit: tried making a pull request instead but it's too much effort to fork the entire repo for such a small change.

**Comment by realCartar** [comment]
literally doesn't matter where it's placed lma0
